apiVersion: v1
kind: Service
metadata:
  name: odoo-backups-lb
  namespace: backups
spec:
  type: LoadBalancer
  selector:
    app: odoo-backups
  ports:
    - name: service
      port: 18080
      targetPort: 8080
