apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: odoo-backups-role
  namespace: backups
rules:
- apiGroups: [""]
  resources: ["pods", "services", "persistentvolumeclaims"]
  verbs: ["get", "list", "create", "delete", "watch"]


---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: odoo-backups-pv-binding
subjects:
- kind: ServiceAccount
  name: odoo-backups-sa
  namespace: backups
roleRef:
  kind: ClusterRole
  name: odoo-backups-pv-role
  apiGroup: rbac.authorization.k8s.io