apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: odoo-backups-role
  namespace: backups
rules:
- apiGroups: [""]
  resources: ["pods", "services", "persistentvolumeclaims"]
  verbs: ["get", "list", "create", "delete", "watch"]
