apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: odoo-backups-binding
  namespace: backups
subjects:
- kind: ServiceAccount
  name: odoo-backups-sa
  namespace: backups
roleRef:
  kind: Role
  name: odoo-backups-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: odoo-backups-pv-role
rules:
- apiGroups: [""]
  resources: ["persistentvolumes"]
  verbs: ["get", "list", "create", "delete", "watch"]